version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"  # Expose container port 80 as host port 5000
    volumes:
      - ./uploads:/app/uploads  # Mount uploads directory for persistence
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount Nginx configuration
